packages:
  - apps/*
catalog:
  "@biomejs/biome": 1.9.4
  "@dotenvx/dotenvx": 1.45.2
  "@t3-oss/env-core": 0.13.8
  "@types/node": 22.16.0
  "@vitest/coverage-v8": 3.2.4
  "hono": 4.8.4
  "knip": 5.61.3
  "tsup": 8.5.0
  "tsx": 4.20.3
  "typescript": 5.8.3
  "vitest": 3.2.4
  "wireit": 0.14.12
  "zod": 3.25.74
  "zod-validation-error": 3.5.2
catalogs:
  api:
    "@hono/node-server": 1.15.0
    "@hono/zod-validator": 0.7.0
    "json-2-csv": 5.5.9
    "kysely": 0.28.2
    "mysql2": 3.14.1
    "nanoid": 5.1.5
    "pino": 9.7.0
    "temporal-polyfill": 0.3.0
  web:
    "react": 19.1.0
    "react-dom": 19.1.0
    "next": 15.3.5
    "nuqs": 2.4.3
    "@types/react": 19.1.8
    "@types/react-dom": 19.1.6
