packages:
  - apps/*
catalog:
  "@biomejs/biome": 1.9.4
  "@dotenvx/dotenvx": 1.51.1
  "@t3-oss/env-core": 0.13.8
  "@types/node": 22.19.0
  "@vitest/coverage-v8": 3.2.4
  "hono": 4.10.4
  "knip": 5.68.0
  "tsup": 8.5.0
  "tsx": 4.20.6
  "typescript": 5.9.3
  "vitest": 3.2.4
  "wireit": 0.14.12
  "zod": 3.25.76
  "zod-validation-error": 3.5.4
catalogs:
  api:
    "@hono/node-server": 1.19.6
    "@hono/zod-validator": 0.7.4
    "json-2-csv": 5.5.10
    "kysely": 0.28.8
    "mysql2": 3.15.3
    "nanoid": 5.1.6
    "pino": 9.14.0
    "temporal-polyfill": 0.3.0
  web:
    "react": 19.2.0
    "react-dom": 19.2.0
    "next": 15.5.6
    "nuqs": 2.7.2
    "@types/react": 19.2.2
    "@types/react-dom": 19.2.2
