packages:
  - apps/*
catalog:
  "@biomejs/biome": 1.9.4
  "@dotenvx/dotenvx": 1.43.0
  "@t3-oss/env-core": 0.13.4
  "@types/node": 22.15.17
  "@vitest/coverage-v8": 3.1.3
  "hono": 4.7.8
  "knip": 5.55.1
  "tsup": 8.4.0
  "tsx": 4.19.4
  "typescript": 5.8.3
  "vitest": 3.1.3
  "wireit": 0.14.12
  "zod": 3.24.4
  "zod-validation-error": 3.4.1
catalogs:
  api:
    "@hono/node-server": 1.14.1
    "@hono/zod-validator": 0.5.0
    "json-2-csv": 5.5.9
    "kysely": 0.28.2
    "mysql2": 3.14.1
    "nanoid": 5.1.5
    "pino": 9.6.0
    "temporal-polyfill": 0.3.0
  web:
    "react": 19.1.0
    "react-dom": 19.1.0
    "next": 15.3.2
    "nuqs": 2.4.3
    "@types/react": 19.1.3
    "@types/react-dom": 19.1.3
