packages:
  - apps/*
catalog:
  "@biomejs/biome": 2.3.7
  "@dotenvx/dotenvx": 1.51.1
  "@t3-oss/env-core": 0.13.8
  "@types/node": 22.19.1
  "@vitest/coverage-v8": 4.0.14
  "hono": 4.10.5
  "knip": 5.69.1
  "tsup": 8.5.1
  "tsx": 4.20.6
  "typescript": 5.9.3
  "vitest": 4.0.14
  "wireit": 0.14.12
  "zod": 4.1.13
  "zod-validation-error": 5.0.0
catalogs:
  api:
    "@hono/node-server": 1.19.6
    "@hono/zod-validator": 0.7.4
    "json-2-csv": 5.5.10
    "kysely": 0.28.8
    "mysql2": 3.15.3
    "nanoid": 5.1.6
    "pino": 10.1.0
    "temporal-polyfill": 0.3.0
  web:
    "react": 19.2.0
    "react-dom": 19.2.0
    "next": 16.0.4
    "nuqs": 2.7.3
    "@types/react": 19.2.4
    "@types/react-dom": 19.2.3
