packages:
  - apps/*
catalog:
  "@biomejs/biome": 1.9.4
  "@dotenvx/dotenvx": 1.41.0
  "@t3-oss/env-core": 0.13.0
  "@types/node": 22.15.2
  "@vitest/coverage-v8": 3.1.2
  "hono": 4.7.7
  "knip": 5.50.5
  "tsup": 8.4.0
  "tsx": 4.19.3
  "typescript": 5.8.3
  "vitest": 3.1.2
  "wireit": 0.14.12
  "zod": 3.24.3
  "zod-validation-error": 3.4.0
catalogs:
  api:
    "@hono/node-server": 1.14.1
    "@hono/zod-validator": 0.4.3
    "json-2-csv": 5.5.9
    "kysely": 0.28.2
    "mysql2": 3.14.1
    "nanoid": 5.1.5
    "pino": 9.6.0
    "temporal-polyfill": 0.3.0
  web:
    "react": 19.1.0
    "react-dom": 19.1.0
    "next": 15.3.1
    "nuqs": 2.4.3
    "@types/react": 19.1.2
    "@types/react-dom": 19.1.2
