packages:
  - apps/*
catalog:
  "@biomejs/biome": 1.9.4
  "@dotenvx/dotenvx": 1.50.1
  "@t3-oss/env-core": 0.13.8
  "@types/node": 22.18.6
  "@vitest/coverage-v8": 3.2.4
  "hono": 4.9.8
  "knip": 5.63.1
  "tsup": 8.5.0
  "tsx": 4.20.5
  "typescript": 5.9.2
  "vitest": 3.2.4
  "wireit": 0.14.12
  "zod": 3.25.76
  "zod-validation-error": 4.0.2
catalogs:
  api:
    "@hono/node-server": 1.19.3
    "@hono/zod-validator": 0.7.3
    "json-2-csv": 5.5.9
    "kysely": 0.28.7
    "mysql2": 3.15.0
    "nanoid": 5.1.5
    "pino": 9.10.0
    "temporal-polyfill": 0.3.0
  web:
    "react": 19.1.1
    "react-dom": 19.1.1
    "next": 15.5.3
    "nuqs": 2.6.0
    "@types/react": 19.1.13
    "@types/react-dom": 19.1.9
