packages:
  - apps/*
catalog:
  "@biomejs/biome": 1.9.4
  "@dotenvx/dotenvx": 1.49.0
  "@t3-oss/env-core": 0.13.8
  "@types/node": 22.17.2
  "@vitest/coverage-v8": 3.2.4
  "hono": 4.9.5
  "knip": 5.63.0
  "tsup": 8.5.0
  "tsx": 4.20.5
  "typescript": 5.9.2
  "vitest": 3.2.4
  "wireit": 0.14.12
  "zod": 3.25.76
  "zod-validation-error": 3.5.3
catalogs:
  api:
    "@hono/node-server": 1.19.1
    "@hono/zod-validator": 0.7.2
    "json-2-csv": 5.5.9
    "kysely": 0.28.5
    "mysql2": 3.14.3
    "nanoid": 5.1.5
    "pino": 9.9.0
    "temporal-polyfill": 0.3.0
  web:
    "react": 19.1.1
    "react-dom": 19.1.1
    "next": 15.5.2
    "nuqs": 2.5.2
    "@types/react": 19.1.11
    "@types/react-dom": 19.1.7
