packages:
  - apps/*
catalog:
  "@biomejs/biome": 1.9.4
  "@dotenvx/dotenvx": 1.39.0
  "@t3-oss/env-core": 0.12.0
  "@types/node": 22.13.17
  "@vitest/coverage-v8": 3.1.1
  "hono": 4.7.5
  "knip": 5.46.4
  "tsup": 8.4.0
  "tsx": 4.19.3
  "typescript": 5.8.2
  "vitest": 3.1.1
  "wireit": 0.14.11
  "zod": 3.24.2
  "zod-validation-error": 3.4.0
catalogs:
  api:
    "@hono/node-server": 1.14.0
    "@hono/zod-validator": 0.4.3
    "json-2-csv": 5.5.9
    "kysely": 0.27.6
    "mysql2": 3.14.0
    "nanoid": 5.1.5
    "pino": 9.6.0
    "temporal-polyfill": 0.3.0
  web:
    "react": 19.1.0
    "react-dom": 19.1.0
    "next": 15.2.4
    "nuqs": 2.4.1
    "@types/react": 19.0.14
    "@types/react-dom": 19.0.6
