packages:
  - apps/*
catalog:
  "@biomejs/biome": 1.9.4
  "@dotenvx/dotenvx": 1.44.1
  "@t3-oss/env-core": 0.13.8
  "@types/node": 22.15.31
  "@vitest/coverage-v8": 3.2.2
  "hono": 4.7.11
  "knip": 5.60.2
  "tsup": 8.5.0
  "tsx": 4.19.4
  "typescript": 5.8.3
  "vitest": 3.2.2
  "wireit": 0.14.12
  "zod": 3.25.57
  "zod-validation-error": 3.4.1
catalogs:
  api:
    "@hono/node-server": 1.14.4
    "@hono/zod-validator": 0.7.0
    "json-2-csv": 5.5.9
    "kysely": 0.28.2
    "mysql2": 3.14.1
    "nanoid": 5.1.5
    "pino": 9.7.0
    "temporal-polyfill": 0.3.0
  web:
    "react": 19.1.0
    "react-dom": 19.1.0
    "next": 15.3.3
    "nuqs": 2.4.3
    "@types/react": 19.1.7
    "@types/react-dom": 19.1.6
