packages:
  - apps/*
catalog:
  "@biomejs/biome": 1.9.4
  "@dotenvx/dotenvx": 1.34.0
  "@t3-oss/env-core": 0.12.0
  "@types/node": 22.13.11
  "@vitest/coverage-v8": 3.0.9
  "hono": 4.6.20
  "knip": 5.43.6
  "tsup": 8.3.6
  "tsx": 4.19.3
  "typescript": 5.7.3
  "vitest": 3.0.9
  "wireit": 0.14.11
  "zod": 3.24.2
  "zod-validation-error": 3.4.0
catalogs:
  api:
    "@hono/node-server": 1.13.8
    "@hono/zod-validator": 0.4.3
    "json-2-csv": 5.5.9
    "kysely": 0.27.6
    "mysql2": 3.12.0
    "nanoid": 5.0.9
    "pino": 9.6.0
    "temporal-polyfill": 0.2.5
  web:
    "react": 19.0.0
    "react-dom": 19.0.0
    "next": 15.1.7
    "nuqs": 2.3.2
    "@types/react": 19.0.8
    "@types/react-dom": 19.0.3
